### PR TITLE
Fix MainMenuBar.createLink

### PR DESCRIPTION
**Pull request by ahie**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-demo/393)

### CODE REVIEW

**Comment by caalador** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/393)*

**Comment by caalador** [comment]
SimpleMenuBar.java needs the same change.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/393#-:-KzTc80HcFPgonUscusF:b-334uvx)*

**Comment by ahie** [comment]
For some reason my eclipse didn't display the correct call hierarchy. Fixed :)

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/393#-:-KzTcnSRApzQ_MH5la2Z:b7utokm)*

**Comment by caalador** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo-static-menu-router/src/main/java/com/vaadin/flow/demo/staticmenu/MainMenuBar.java, line 75 at r1](https://reviewable.io:443/reviews/vaadin/flow-demo/393#-KzTcl_510ymn30_ycyB:-KzTcl_510ymn30_ycyC:bwqmwkn) ([raw file](https://github.com/vaadin/flow-demo/blob/18348754a7bc376d80993c47d7fe6849d2e45047/demo-static-menu-router/src/main/java/com/vaadin/flow/demo/staticmenu/MainMenuBar.java#L75)):*
> targets.put((Class<? extends Component>) navigationTarget, link);
>         targetPaths.put(link.getHref(),
>                 (Class<? extends Component>) navigationTarget);
There not needed casts could have also been removed, but not a blocker.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/393)*

**Comment by caalador** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/393)*

**Comment by caalador** [comment]
Pöh. demo-dynamic-menu, `MenuItemComponent` -> 
```
    public <C extends Component & HasUrlParameter<Integer>> MenuItemComponent(
            Class<C> viewClass, int id, String name) {
```

Then everything should compile

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/393#-:-KzTe9LhbOs-rApWsOsR:bnvmkxv)*

**Comment by caalador** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/393)*

**Pull request merged**
