### PR TITLE
Fix demo compilation

### PR DESCRIPTION
**Pull request by caalador**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-demo/409)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/409)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/409)*

**Comment by SomeoneToIgnore** [comment]
Nice incremental fix approach ;)

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/409#-:-L3DRC7fIK2DSXl4RxXm:b-kj1grt)*

**Comment by caalador** [comment]
( =_=' )

Idea had some problems with updating the maven snapshots to all as it sees them as singular projects and reimport only did the one module... =_=

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/409#-:-L3DRaG-cYaOoNxupCpE:bw3sov5)*

**Pull request merged**
