### PR TITLE
Fix failing demo build due to update of TB

### PR DESCRIPTION
**Pull request by caalador**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-demo/398)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/398)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/398)*

**Comment by SomeoneToIgnore** [comment]
*[demo-jquery-table/pom.xml, line 45 at r2](https://reviewable.io:443/reviews/vaadin/flow-demo/398#-L-W-uwEfi-npfthw18b:-L-W-uwEfi-npfthw18c:bx0lbe3) ([raw file](https://github.com/vaadin/flow-demo/blob/fad1273d7d5df2fe1788450a987583752f53ae2a/demo-jquery-table/pom.xml#L45)):*
> ```XML
>             <groupId>com.google.guava</groupId>
>             <artifactId>guava</artifactId>
>             <version>22.0</version>
> ```

Since the version is duplicated in couple of files already and supposed to be the same, would it make sense to extract it to the root pom as a parameter?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/398)*

**Comment by caalador** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo-jquery-table/pom.xml, line 45 at r2](https://reviewable.io:443/reviews/vaadin/flow-demo/398#-L-W-uwEfi-npfthw18b:-L-W2olcYkulcEBaEJka:b-896fix) ([raw file](https://github.com/vaadin/flow-demo/blob/fad1273d7d5df2fe1788450a987583752f53ae2a/demo-jquery-table/pom.xml#L45)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

Since the version is duplicated in couple of files already and supposed to be the same, would it make sense to extract it to the root pom as a parameter?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/398)*

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/398#-:-L-W2zWbN2HFdaE1OTGS:bnfp4nl)*

**Pull request merged**
