### PR TITLE
Fixes multi-projects' tests failure under productionMode

### PR DESCRIPTION
**Pull request by ZheSun88**
But still after, this got merged, the project `demo-jquery-table` has tests failing under productionMode

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-demo/442)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---

*[demo-date-field/src/main/java/com/vaadin/flow/demo/datefield/customelement/ApplicationServlet.java, line 18 at r1](https://reviewable.io/reviews/vaadin/flow-demo/442#-LB10qz_4fqwSAmfnxKP:-LB10qzbChZMaiXwcOA7:b-d0wxhj) ([raw file](https://github.com/vaadin/flow-demo/blob/68ee2dad9806913777d9c3e1da31b697460aeb7e/demo-date-field/src/main/java/com/vaadin/flow/demo/datefield/customelement/ApplicationServlet.java#L18)):*
> ```Java
> @VaadinServletConfiguration(productionMode = false)
> public class ApplicationServlet extends VaadinServlet {
> }
> ```

new line

---

*[demo-textfield-composite/src/main/java/com/vaadin/flow/demo/textfieldcomposite/ApplicationServlet.java, line 18 at r1](https://reviewable.io/reviews/vaadin/flow-demo/442#-LB11-e791u1YONm1E0r:-LB11-e791u1YONm1E0s:b-d0wxhj) ([raw file](https://github.com/vaadin/flow-demo/blob/68ee2dad9806913777d9c3e1da31b697460aeb7e/demo-textfield-composite/src/main/java/com/vaadin/flow/demo/textfieldcomposite/ApplicationServlet.java#L18)):*
> ```Java
> @VaadinServletConfiguration(productionMode = false)
> public class ApplicationServlet extends VaadinServlet {
> }
> ```

new line

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-demo/442#-:-LB111gj5cDp1FfyUUc7:bnfp4nl)*

**Comment by ZheSun88** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[demo-date-field/src/main/java/com/vaadin/flow/demo/datefield/customelement/ApplicationServlet.java, line 18 at r1](https://reviewable.io/reviews/vaadin/flow-demo/442#-LB10qz_4fqwSAmfnxKP:-LB1Qv1I9VmjG4MFEIuY:b-896fix) ([raw file](https://github.com/vaadin/flow-demo/blob/68ee2dad9806913777d9c3e1da31b697460aeb7e/demo-date-field/src/main/java/com/vaadin/flow/demo/datefield/customelement/ApplicationServlet.java#L18)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

new line
</blockquote></details>

Done.

---

*[demo-textfield-composite/src/main/java/com/vaadin/flow/demo/textfieldcomposite/ApplicationServlet.java, line 18 at r1](https://reviewable.io/reviews/vaadin/flow-demo/442#-LB11-e791u1YONm1E0r:-LB1Qvhj2gOASMwzA12M:b-896fix) ([raw file](https://github.com/vaadin/flow-demo/blob/68ee2dad9806913777d9c3e1da31b697460aeb7e/demo-textfield-composite/src/main/java/com/vaadin/flow/demo/textfieldcomposite/ApplicationServlet.java#L18)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

new line
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-demo/442)*

**Comment by gilberto-torrezan** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-demo/442)*

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-demo/442#-:-LB4bcIe03EWupr4eBMj:bnfp4nl)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/flow-demo/442#-:-LB5E_FCBJJLPHPSZlr3:bnfp4nl)*

**Pull request merged**
