### PR TITLE
Localisation demo

### PR DESCRIPTION
**Pull request by caalador**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-demo/383)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 23 of 23 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[demo-static-menu-router/src/main/java/com/vaadin/flow/demo/staticmenu/community/blog/BlogList.java, line 39 at r1](https://reviewable.io:443/reviews/vaadin/flow-demo/383#-KyZmmar95V7_Q8GaWEb:-KyZmmar95V7_Q8GaWEc:b-2cq153) ([raw file](https://github.com/vaadin/flow-demo/blob/f6efc3a41a94d5cc1362e0e8ffab6c0e86110779/demo-static-menu-router/src/main/java/com/vaadin/flow/demo/staticmenu/community/blog/BlogList.java#L39)):*
> add_blog_post;

Camel case is not that good anymore ? :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/383)*

**Comment by caalador** [comment]
Review status: 22 of 23 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo-static-menu-router/src/main/java/com/vaadin/flow/demo/staticmenu/community/blog/BlogList.java, line 39 at r1](https://reviewable.io:443/reviews/vaadin/flow-demo/383#-KyZmmar95V7_Q8GaWEb:-KyZqGYgGaec710HRu_t:bz4p3qt) ([raw file](https://github.com/vaadin/flow-demo/blob/f6efc3a41a94d5cc1362e0e8ffab6c0e86110779/demo-static-menu-router/src/main/java/com/vaadin/flow/demo/staticmenu/community/blog/BlogList.java#L39)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> add_blog_post;

Camel case is not that good anymore ? :)
</blockquote></details>

I have no idea what happened there. Probably unconsciously trying to be hip and non mainstream. =)
Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/383)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/383)*

**Comment by denis-anisimov** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/383)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/383)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/383)*

**Comment by denis-anisimov** [comment]
Reviewed 4 of 4 files at r6.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/383)*

**Pull request merged**
