### PR TITLE
Bump master to Flow 3.2 and remove jquerytable

### LINKED ISSUE #473: Flow demo nightly validation build fails
https://bender.vaadin.com/viewLog.html?buildId=141139&tab=buildResultsDiv&buildTypeId=Flow_FlowDemoSnapshots

### PR DESCRIPTION
**Pull request by pleku**
Fixes #473 

This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-demo/474)

### CODE REVIEW

**Comment by pleku** [comment]
Do not squash please

**Comment by bogdanudrescu** [comment]
Failing with `[Step 3/5] Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact com.vaadin:flow-server-compatibility-mode:jar:3.2-SNAPSHOT in vaadin-snapshots (https://oss.sonatype.org/content/repositories/vaadin-snapshots/)`

**Comment by caalador** [comment]
Will this be worked on or should it be closed?

**Comment by pleku** [comment]
Could be worked on when it is a priority again from other tasks. Doesn't need to be open though

**Pull request closed without merging**
