### PR TITLE
Demo for registerred routes.

### PR DESCRIPTION
**Pull request by caalador**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-demo/404)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[demo-route-menu/pom.xml, line 148 at r1](https://reviewable.io:443/reviews/vaadin/flow-demo/404#-L0yLJg-QhgXK06K4rsL:-L0yLJg-QhgXK06K4rsM:b-d0wxhj) ([raw file](https://github.com/vaadin/flow-demo/blob/9b06d13c578206b16d7fe587e9c935136c290109/demo-route-menu/pom.xml#L148)):*
> ```XML
> 
> 
> </project>
> ```

new line

---

*[demo-route-menu/src/main/java/com/vaadin/flow/demo/menu/MenuBar.java, line 46 at r1](https://reviewable.io:443/reviews/vaadin/flow-demo/404#-L0yLgxKusWHoPZ2F6nb:-L0yLgxKusWHoPZ2F6nc:b-j0biuf) ([raw file](https://github.com/vaadin/flow-demo/blob/9b06d13c578206b16d7fe587e9c935136c290109/demo-route-menu/src/main/java/com/vaadin/flow/demo/menu/MenuBar.java#L46)):*
> parentLayouts.remove(UI.class);

May be just filter in the stream above before collect ?

---

*[demo-route-menu/src/main/java/com/vaadin/flow/demo/menu/MenuBar.java, line 49 at r1](https://reviewable.io:443/reviews/vaadin/flow-demo/404#-L0yL_8ZRyRq-_qTuFIF:-L0yL_8ZRyRq-_qTuFIG:bu8llgk) ([raw file](https://github.com/vaadin/flow-demo/blob/9b06d13c578206b16d7fe587e9c935136c290109/demo-route-menu/src/main/java/com/vaadin/flow/demo/menu/MenuBar.java#L49)):*
> o1.equals(UI.class)

The line above removes the `UI` instance from the list.
Are you sure you need this code here?

---

*[demo-route-menu/src/main/java/com/vaadin/flow/demo/menu/MenuBar.java, line 63 at r1](https://reviewable.io:443/reviews/vaadin/flow-demo/404#-L0yLrq-Ljby2kjmF6AB:-L0yLrq-Ljby2kjmF6AC:bglv8ds) ([raw file](https://github.com/vaadin/flow-demo/blob/9b06d13c578206b16d7fe587e9c935136c290109/demo-route-menu/src/main/java/com/vaadin/flow/demo/menu/MenuBar.java#L63)):*
> route -> {
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>
>                 RouterLink routerLink = new RouterLink(getRouteName(route),
>                         route.getNavigationTarget());
>                 // ApplicationLayout children should be as root targets.
>                 if (key.equals(ApplicationLayout.class)) {
</details>

Long lamda inside lambda.

---

*[demo-route-menu/src/main/java/com/vaadin/flow/demo/menu/MenuBar.java, line 66 at r1](https://reviewable.io:443/reviews/vaadin/flow-demo/404#-L0yLlvBQhEKSjx1S55m:-L0yLlvCLLKsf0DsyKU8:b-3uh0z8) ([raw file](https://github.com/vaadin/flow-demo/blob/9b06d13c578206b16d7fe587e9c935136c290109/demo-route-menu/src/main/java/com/vaadin/flow/demo/menu/MenuBar.java#L66)):*
> ListItem listItem = new ListItem();
<details><summary><i alt="summary">Quoted 22 lines of code…</i></summary>
>             UnorderedList subList = new UnorderedList();
>             routes.get(key).forEach(route -> {
>                 RouterLink routerLink = new RouterLink(getRouteName(route),
>                         route.getNavigationTarget());
>                 // ApplicationLayout children should be as root targets.
>                 if (key.equals(ApplicationLayout.class)) {
>                     ListItem menuItem = new ListItem(routerLink);
>                     add(menuItem);
>                 } else {
>                     subList.add(new ListItem(routerLink));
>                 }
>             });
>             if (subList.getChildren().count() != 0) {
>                 String title = key.getSimpleName();
>                 if (key.isAnnotationPresent(PageTitle.class)) {
>                     title = key.getAnnotation(PageTitle.class).value();
>                 }
>                 Anchor anchor = new Anchor("#", title);
>                 listItem.add(anchor);
>                 listItem.add(subList);
>                 add(listItem);
>             }
</details>

Very long not readable lambda.

---

*[demo-route-menu/src/main/java/com/vaadin/flow/demo/menu/MenuBar.java, line 94 at r1](https://reviewable.io:443/reviews/vaadin/flow-demo/404#-L0yLyuin9HW1G-Yp9Uv:-L0yLyuin9HW1G-Yp9Uw:b87ewm0) ([raw file](https://github.com/vaadin/flow-demo/blob/9b06d13c578206b16d7fe587e9c935136c290109/demo-route-menu/src/main/java/com/vaadin/flow/demo/menu/MenuBar.java#L94)):*
> route -> {
>                 external.add(route.getNavigationTarget());
>  
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>
>                 String routeName = getRouteName(route);
>                 RouterLink routerLink = new RouterLink(
>                         routeName.substring(0, routeName.indexOf("View")),
>                         route.getNavigationTarget());
>                 subList.add(new ListItem(routerLink));
>             })
</details>

Please extract this lambda as a method.

---

*[demo-route-menu/src/main/webapp/frontend/styles.css, line 0 at r1](https://reviewable.io:443/reviews/vaadin/flow-demo/404#-L0yMFHliXTiTnMCkRhV:-L0yMFHliXTiTnMCkRhW:b-ytgkux) ([raw file](https://github.com/vaadin/flow-demo/blob/9b06d13c578206b16d7fe587e9c935136c290109/demo-route-menu/src/main/webapp/frontend/styles.css#L0)):*
Empty ?

---

*[demo-route-menu/src/main/webapp/frontend/styles/styles.css, line 89 at r1](https://reviewable.io:443/reviews/vaadin/flow-demo/404#-L0yMLojeuZBwY7-Yanb:-L0yMLojeuZBwY7-Yanc:b-d0wxhj) ([raw file](https://github.com/vaadin/flow-demo/blob/9b06d13c578206b16d7fe587e9c935136c290109/demo-route-menu/src/main/webapp/frontend/styles/styles.css#L89)):*
> ```CSS
>     -webkit-transform: rotate(45deg);
>     transform: rotate(45deg);
> }
> ```

new line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/404)*

**Comment by caalador** [comment]
Review status: 8 of 11 files reviewed at latest revision, 8 unresolved discussions.

---

*[demo-route-menu/pom.xml, line 148 at r1](https://reviewable.io:443/reviews/vaadin/flow-demo/404#-L0yLJg-QhgXK06K4rsL:-L0yTDXvxXLWn_LTj2wN:b-896fix) ([raw file](https://github.com/vaadin/flow-demo/blob/9b06d13c578206b16d7fe587e9c935136c290109/demo-route-menu/pom.xml#L148)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

new line
</blockquote></details>

Done.

---

*[demo-route-menu/src/main/java/com/vaadin/flow/demo/menu/MenuBar.java, line 46 at r1](https://reviewable.io:443/reviews/vaadin/flow-demo/404#-L0yLgxKusWHoPZ2F6nb:-L0yTX-CnDN1FQMsxSat:b-896fix) ([raw file](https://github.com/vaadin/flow-demo/blob/9b06d13c578206b16d7fe587e9c935136c290109/demo-route-menu/src/main/java/com/vaadin/flow/demo/menu/MenuBar.java#L46)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> parentLayouts.remove(UI.class);

May be just filter in the stream above before collect ?
</blockquote></details>

Done.

---

*[demo-route-menu/src/main/java/com/vaadin/flow/demo/menu/MenuBar.java, line 49 at r1](https://reviewable.io:443/reviews/vaadin/flow-demo/404#-L0yL_8ZRyRq-_qTuFIF:-L0yTXN5OySc6lfWTQUM:b-896fix) ([raw file](https://github.com/vaadin/flow-demo/blob/9b06d13c578206b16d7fe587e9c935136c290109/demo-route-menu/src/main/java/com/vaadin/flow/demo/menu/MenuBar.java#L49)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> o1.equals(UI.class)

The line above removes the `UI` instance from the list.
Are you sure you need this code here?
</blockquote></details>

Done.

---

*[demo-route-menu/src/main/java/com/vaadin/flow/demo/menu/MenuBar.java, line 63 at r1](https://reviewable.io:443/reviews/vaadin/flow-demo/404#-L0yLrq-Ljby2kjmF6AB:-L0yVASWINDk9HY5fL7z:b-896fix) ([raw file](https://github.com/vaadin/flow-demo/blob/9b06d13c578206b16d7fe587e9c935136c290109/demo-route-menu/src/main/java/com/vaadin/flow/demo/menu/MenuBar.java#L63)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> route -> {
>                 RouterLink routerLink = new RouterLink(getRouteName(route),
>                         route.getNavigationTarget());
>                 // ApplicationLayout children should be as root targets.
>                 if (key.equals(ApplicationLayout.class)) {

Long lamda inside lambda.
</blockquote></details>

Done.

---

*[demo-route-menu/src/main/java/com/vaadin/flow/demo/menu/MenuBar.java, line 66 at r1](https://reviewable.io:443/reviews/vaadin/flow-demo/404#-L0yLlvBQhEKSjx1S55m:-L0yVA7JGcJnRDdC3Qkx:b-896fix) ([raw file](https://github.com/vaadin/flow-demo/blob/9b06d13c578206b16d7fe587e9c935136c290109/demo-route-menu/src/main/java/com/vaadin/flow/demo/menu/MenuBar.java#L66)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ListItem listItem = new ListItem();
>             UnorderedList subList = new UnorderedList();
>             routes.get(key).forEach(route -> {
>                 RouterLink routerLink = new RouterLink(getRouteName(route),
>                         route.getNavigationTarget());
>                 // ApplicationLayout children should be as root targets.
>                 if (key.equals(ApplicationLayout.class)) {
>                     ListItem menuItem = new ListItem(routerLink);
>                     add(menuItem);
>                 } else {
>                     subList.add(new ListItem(routerLink));
>                 }
>             });
>             if (subList.getChildren().count() != 0) {
>                 String title = key.getSimpleName();
>                 if (key.isAnnotationPresent(PageTitle.class)) {
>                     title = key.getAnnotation(PageTitle.class).value();
>                 }
>                 Anchor anchor = new Anchor("#", title);
>                 listItem.add(anchor);
>                 listItem.add(subList);
>                 add(listItem);
>             }

Very long not readable lambda.
</blockquote></details>

Done.

---

*[demo-route-menu/src/main/java/com/vaadin/flow/demo/menu/MenuBar.java, line 94 at r1](https://reviewable.io:443/reviews/vaadin/flow-demo/404#-L0yLyuin9HW1G-Yp9Uv:-L0yV9vd0RNA3oEupSPd:b-896fix) ([raw file](https://github.com/vaadin/flow-demo/blob/9b06d13c578206b16d7fe587e9c935136c290109/demo-route-menu/src/main/java/com/vaadin/flow/demo/menu/MenuBar.java#L94)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> route -> {
>                 external.add(route.getNavigationTarget());
>  
>                 String routeName = getRouteName(route);
>                 RouterLink routerLink = new RouterLink(
>                         routeName.substring(0, routeName.indexOf("View")),
>                         route.getNavigationTarget());
>                 subList.add(new ListItem(routerLink));
>             })

Please extract this lambda as a method.
</blockquote></details>

Done.

---

*[demo-route-menu/src/main/webapp/frontend/styles/styles.css, line 89 at r1](https://reviewable.io:443/reviews/vaadin/flow-demo/404#-L0yMLojeuZBwY7-Yanb:-L0yTuZdQplSkRzdkjjJ:b-896fix) ([raw file](https://github.com/vaadin/flow-demo/blob/9b06d13c578206b16d7fe587e9c935136c290109/demo-route-menu/src/main/webapp/frontend/styles/styles.css#L89)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

new line
</blockquote></details>

Done.

---

*[demo-route-menu/src/main/webapp/frontend/styles.css, line  at r1](https://reviewable.io:443/reviews/vaadin/flow-demo/404#-L0yMFHliXTiTnMCkRhV:-L0yToJqmU0YdLLI_jjJ:btw2ufr) ([raw file](https://github.com/vaadin/flow-demo/blob/9b06d13c578206b16d7fe587e9c935136c290109/demo-route-menu/src/main/webapp/frontend/styles.css#L)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Empty ?
</blockquote></details>

Tried to fix the Icons demo, but decided to remove it.
Deleted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/404)*

**Comment by denis-anisimov** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/404)*

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 2 files at r3.
Review status: 5 of 12 files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/404)*

**Comment by gilberto-torrezan** [comment]
Reviewed 3 of 12 files at r1, 1 of 4 files at r2, 1 of 2 files at r3, 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/404)*

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/404#-:-L1uwDr2_8vc3SQtd2Pt:bnfp4nl)*

**Pull request merged**
