### PR TITLE
Remove old Router from project

### PR DESCRIPTION
**Pull request by ZheSun88**
related flow issue vaadin/flow#3826

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-demo/433)

### CODE REVIEW

**Comment by ZheSun88** [comment]
Review status: 13 of 20 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo-web-site/src/main/java/com/vaadin/flow/demo/website/SimpleView.java, line 45 at r1](https://beta.reviewable.io/reviews/vaadin/flow-demo/433#-L9Q6Luy1POQOeOZquP6:-L9QSMWwDZO-TUg7zJta:b-g97t1w) ([raw file](https://github.com/vaadin/flow-demo/blob/70935f6591f33f0a9a59e6b92560f56e761642b0/demo-web-site/src/main/java/com/vaadin/flow/demo/website/SimpleView.java#L45)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

This title is not dynamic at all. You can use the `@PageTitle` annotation instead and remove the `HasDynamicTitle` inheritance. 
</blockquote></details>

No i didn't remove this, because this class is the super class for all the other views. if using "@PageTitle", as it states in the documentation, `The @PageTitle annotation is read from the actual navigation target only; neither its superclasses nor its parent views are considered.` the title will null for other views. and the tests for checking this will fail also.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-demo/433)*

**Comment by denis-anisimov** [comment]
Reviewed 12 of 13 files at r1, 2 of 7 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks broke.

---

*[demo-google-signin/src/main/java/com/vaadin/flow/demo/googlesignin/component/SigninUI.java, line 26 at r3](https://beta.reviewable.io/reviews/vaadin/flow-demo/433#-L9cw8hg8y-iR3GOZrgN:-L9cw8hg8y-iR3GOZrgO:bcweera) ([raw file](https://github.com/vaadin/flow-demo/blob/e36e89968570f38155b4ac7678468d24ff745889/demo-google-signin/src/main/java/com/vaadin/flow/demo/googlesignin/component/SigninUI.java#L26)):*
> ```
> SigninUI 
> ```

It's not `UI` anymore.

---

*[demo-google-signin/src/main/java/com/vaadin/flow/demo/googlesignin/component/SigninUI.java, line 29 at r3](https://beta.reviewable.io/reviews/vaadin/flow-demo/433#-L9cwBTK0PFR4sJpKBgJ:-L9cwBTK0PFR4sJpKBgK:bdxhbua) ([raw file](https://github.com/vaadin/flow-demo/blob/e36e89968570f38155b4ac7678468d24ff745889/demo-google-signin/src/main/java/com/vaadin/flow/demo/googlesignin/component/SigninUI.java#L29)):*
> ```
> Create UI 
> ```

It's not a `UI`

---

*[demo-google-signin/src/main/java/com/vaadin/flow/demo/googlesignin/component/SigninUI.java, line 32 at r3](https://beta.reviewable.io/reviews/vaadin/flow-demo/433#-L9cwH6FDbxquWMTowp7:-L9cwH6FDbxquWMTowp8:b-p03wc2) ([raw file](https://github.com/vaadin/flow-demo/blob/e36e89968570f38155b4ac7678468d24ff745889/demo-google-signin/src/main/java/com/vaadin/flow/demo/googlesignin/component/SigninUI.java#L32)):*
> ```
> new SigninView()
> ```

This is the only element inside this former `UI`.
It makes sense to remove this class at all and add `@Route` to the view.

---

*[demo-jquery-table/src/main/java/com/vaadin/flow/demo/jquerytable/page/DemoUI.java, line 33 at r3](https://beta.reviewable.io/reviews/vaadin/flow-demo/433#-L9cwa3M5w9aUp9iRjMa:-L9cwa3M5w9aUp9iRjMb:b-3m6pva) ([raw file](https://github.com/vaadin/flow-demo/blob/e36e89968570f38155b4ac7678468d24ff745889/demo-jquery-table/src/main/java/com/vaadin/flow/demo/jquerytable/page/DemoUI.java#L33)):*
> ```
> ui = DemoUI.class
> ```

How does it work ?
Does `DemoUI`  overrides  something ?
If it's used to show a content the `UI` should be removed and the `@Route` annotation used.

---

*[demo-minesweeper-component/src/main/java/com/vaadin/flow/demo/minesweeper/component/MinesweeperUI.java, line 32 at r3](https://beta.reviewable.io/reviews/vaadin/flow-demo/433#-L9cwsplDeHMWWqDT7ul:-L9cwsplDeHMWWqDT7um:bszi3wa) ([raw file](https://github.com/vaadin/flow-demo/blob/e36e89968570f38155b4ac7678468d24ff745889/demo-minesweeper-component/src/main/java/com/vaadin/flow/demo/minesweeper/component/MinesweeperUI.java#L32)):*
> ```
> MinesweeperUI
> ```

Not a `UI` anymore.

---

*[demo-minesweeper-element/src/main/java/com/vaadin/flow/demo/minesweeper/element/MinesweeperUI.java, line 31 at r3](https://beta.reviewable.io/reviews/vaadin/flow-demo/433#-L9cwyPu0zvpJ3ieo25a:-L9cwyPu0zvpJ3ieo25b:b9l9hio) ([raw file](https://github.com/vaadin/flow-demo/blob/e36e89968570f38155b4ac7678468d24ff745889/demo-minesweeper-element/src/main/java/com/vaadin/flow/demo/minesweeper/element/MinesweeperUI.java#L31)):*
> ```
> MinesweeperUI 
> ```

No a `UI` anymore.

---

*[demo-textfield-component/src/main/java/com/vaadin/flow/demo/textfieldcomponent/TextFieldUI.java, line 25 at r3](https://beta.reviewable.io/reviews/vaadin/flow-demo/433#-L9cx8cH3MvgB1sONGnw:-L9cx8cH3MvgB1sONGnx:b-w8dzzf) ([raw file](https://github.com/vaadin/flow-demo/blob/e36e89968570f38155b4ac7678468d24ff745889/demo-textfield-component/src/main/java/com/vaadin/flow/demo/textfieldcomponent/TextFieldUI.java#L25)):*
> ```
> TextFieldUI
> ```

No a `UI`  anymore.

---

*[demo-textfield-composite/src/main/java/com/vaadin/flow/demo/textfieldcomposite/TextFieldUI.java, line 25 at r3](https://beta.reviewable.io/reviews/vaadin/flow-demo/433#-L9cxEW1-NUOCs8E6ODX:-L9cxEW1-NUOCs8E6ODY:b-arpln9) ([raw file](https://github.com/vaadin/flow-demo/blob/e36e89968570f38155b4ac7678468d24ff745889/demo-textfield-composite/src/main/java/com/vaadin/flow/demo/textfieldcomposite/TextFieldUI.java#L25)):*
> ```
> TextFieldUI
> ```


No a `UI` anymore.

---

*[demo-textfield-composite/src/main/java/com/vaadin/flow/demo/textfieldcomposite/TextFieldUI.java, line 28 at r3](https://beta.reviewable.io/reviews/vaadin/flow-demo/433#-L9cxIdm56KJOqXW1iYB:-L9cxIdm56KJOqXW1iYC:b-jklet1) ([raw file](https://github.com/vaadin/flow-demo/blob/e36e89968570f38155b4ac7678468d24ff745889/demo-textfield-composite/src/main/java/com/vaadin/flow/demo/textfieldcomposite/TextFieldUI.java#L28)):*
> ```
>  Create UI for 
> ```


Not a `UI` anymore.

---

*[demo-web-site/src/main/java/com/vaadin/flow/demo/website/HomeView.java, line 31 at r3](https://beta.reviewable.io/reviews/vaadin/flow-demo/433#-L9cxU4u20yNJLzD_zHE:-L9cxU4u20yNJLzD_zHF:bu6ux3v) ([raw file](https://github.com/vaadin/flow-demo/blob/5169ce78da43fc2cef44d82848a65113ef565757/demo-web-site/src/main/java/com/vaadin/flow/demo/website/HomeView.java#L31)):*
> ```
> add(getMappingInfo(SiteRouterConfigurator.MAPPING_HOME));
> ```

Why is it just removed without a replacement ?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-demo/433)*

**Comment by gilberto-torrezan** [comment]
Reviewed 2 of 7 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 18 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-demo/433)*

**Comment by ZheSun88** [comment]
Review status: 8 of 21 files reviewed at latest revision, 13 unresolved discussions.

---

*[demo-google-signin/src/main/java/com/vaadin/flow/demo/googlesignin/component/SigninUI.java, line 26 at r3](https://beta.reviewable.io/reviews/vaadin/flow-demo/433#-L9cw8hg8y-iR3GOZrgN:-L9dr8dhANDwknEQ_8OW:bntv4u9) ([raw file](https://github.com/vaadin/flow-demo/blob/e36e89968570f38155b4ac7678468d24ff745889/demo-google-signin/src/main/java/com/vaadin/flow/demo/googlesignin/component/SigninUI.java#L26)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> SigninUI 
> ```

It's not `UI` anymore.
</blockquote></details>

file removed

---

*[demo-google-signin/src/main/java/com/vaadin/flow/demo/googlesignin/component/SigninUI.java, line 29 at r3](https://beta.reviewable.io/reviews/vaadin/flow-demo/433#-L9cwBTK0PFR4sJpKBgJ:-L9drBPtCrk3yBM8_e7g:bntv4u9) ([raw file](https://github.com/vaadin/flow-demo/blob/e36e89968570f38155b4ac7678468d24ff745889/demo-google-signin/src/main/java/com/vaadin/flow/demo/googlesignin/component/SigninUI.java#L29)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> Create UI 
> ```

It's not a `UI`
</blockquote></details>

file removed

---

*[demo-google-signin/src/main/java/com/vaadin/flow/demo/googlesignin/component/SigninUI.java, line 32 at r3](https://beta.reviewable.io/reviews/vaadin/flow-demo/433#-L9cwH6FDbxquWMTowp7:-L9drXpf0JjZ-ZhAXCEI:bb7f2mf) ([raw file](https://github.com/vaadin/flow-demo/blob/e36e89968570f38155b4ac7678468d24ff745889/demo-google-signin/src/main/java/com/vaadin/flow/demo/googlesignin/component/SigninUI.java#L32)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> new SigninView()
> ```

This is the only element inside this former `UI`.
It makes sense to remove this class at all and add `@Route` to the view.
</blockquote></details>

done

---

*[demo-jquery-table/src/main/java/com/vaadin/flow/demo/jquerytable/page/DemoUI.java, line 33 at r3](https://beta.reviewable.io/reviews/vaadin/flow-demo/433#-L9cwa3M5w9aUp9iRjMa:-L9drGlO7P-zlQqL5QWh:blh34u3) ([raw file](https://github.com/vaadin/flow-demo/blob/e36e89968570f38155b4ac7678468d24ff745889/demo-jquery-table/src/main/java/com/vaadin/flow/demo/jquerytable/page/DemoUI.java#L33)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> ui = DemoUI.class
> ```

How does it work ?
Does `DemoUI`  overrides  something ?
If it's used to show a content the `UI` should be removed and the `@Route` annotation used.
</blockquote></details>

removed the unnecessary servlet Config

---

*[demo-web-site/src/main/java/com/vaadin/flow/demo/website/HomeView.java, line 31 at r3](https://beta.reviewable.io/reviews/vaadin/flow-demo/433#-L9cxU4u20yNJLzD_zHE:-L9drRau5SPRAOIeXkRx:b-g6910r) ([raw file](https://github.com/vaadin/flow-demo/blob/5169ce78da43fc2cef44d82848a65113ef565757/demo-web-site/src/main/java/com/vaadin/flow/demo/website/HomeView.java#L31)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> add(getMappingInfo(SiteRouterConfigurator.MAPPING_HOME));
> ```

Why is it just removed without a replacement ?
</blockquote></details>

re-added 

---

*[demo-minesweeper-component/src/main/java/com/vaadin/flow/demo/minesweeper/component/MinesweeperUI.java, line 32 at r3](https://beta.reviewable.io/reviews/vaadin/flow-demo/433#-L9cwsplDeHMWWqDT7ul:-L9drMX_1FarJmzKg_Lw:bb7f2mf) ([raw file](https://github.com/vaadin/flow-demo/blob/e36e89968570f38155b4ac7678468d24ff745889/demo-minesweeper-component/src/main/java/com/vaadin/flow/demo/minesweeper/component/MinesweeperUI.java#L32)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> MinesweeperUI
> ```

Not a `UI` anymore.
</blockquote></details>

done

---

*[demo-minesweeper-element/src/main/java/com/vaadin/flow/demo/minesweeper/element/MinesweeperUI.java, line 31 at r3](https://beta.reviewable.io/reviews/vaadin/flow-demo/433#-L9cwyPu0zvpJ3ieo25a:-L9drNcE87QTKauDYUeF:bb7f2mf) ([raw file](https://github.com/vaadin/flow-demo/blob/e36e89968570f38155b4ac7678468d24ff745889/demo-minesweeper-element/src/main/java/com/vaadin/flow/demo/minesweeper/element/MinesweeperUI.java#L31)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> MinesweeperUI 
> ```

No a `UI` anymore.
</blockquote></details>

done

---

*[demo-textfield-component/src/main/java/com/vaadin/flow/demo/textfieldcomponent/TextFieldUI.java, line 25 at r3](https://beta.reviewable.io/reviews/vaadin/flow-demo/433#-L9cx8cH3MvgB1sONGnw:-L9drP500NiSQl_RxOP2:bb7f2mf) ([raw file](https://github.com/vaadin/flow-demo/blob/e36e89968570f38155b4ac7678468d24ff745889/demo-textfield-component/src/main/java/com/vaadin/flow/demo/textfieldcomponent/TextFieldUI.java#L25)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> TextFieldUI
> ```

No a `UI`  anymore.
</blockquote></details>

done

---

*[demo-textfield-composite/src/main/java/com/vaadin/flow/demo/textfieldcomposite/TextFieldUI.java, line 25 at r3](https://beta.reviewable.io/reviews/vaadin/flow-demo/433#-L9cxEW1-NUOCs8E6ODX:-L9drPwZ4JzCqZUcNxUO:bb7f2mf) ([raw file](https://github.com/vaadin/flow-demo/blob/e36e89968570f38155b4ac7678468d24ff745889/demo-textfield-composite/src/main/java/com/vaadin/flow/demo/textfieldcomposite/TextFieldUI.java#L25)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> TextFieldUI
> ```


No a `UI` anymore.
</blockquote></details>

done

---

*[demo-textfield-composite/src/main/java/com/vaadin/flow/demo/textfieldcomposite/TextFieldUI.java, line 28 at r3](https://beta.reviewable.io/reviews/vaadin/flow-demo/433#-L9cxIdm56KJOqXW1iYB:-L9drQfbAYw8ffFfKpgB:bb7f2mf) ([raw file](https://github.com/vaadin/flow-demo/blob/e36e89968570f38155b4ac7678468d24ff745889/demo-textfield-composite/src/main/java/com/vaadin/flow/demo/textfieldcomposite/TextFieldUI.java#L28)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
>  Create UI for 
> ```


Not a `UI` anymore.
</blockquote></details>

done

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-demo/433)*

**Comment by denis-anisimov** [comment]
Reviewed 17 of 21 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-demo/433)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-demo/433#-:-L9duCLw9vcUoFGHERCJ:bnfp4nl)*

**Pull request merged**
