### PR TITLE
Update flow-demo using new webjars

### PR DESCRIPTION
**Pull request by ZheSun88**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-demo/414)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
*[pom.xml, line 171 at r1](https://reviewable.io:443/reviews/vaadin/flow-demo/414#-L4eVktNdgVwomTRE19b:-L4eVktNdgVwomTRE19c:b-48j5tt) ([raw file](https://github.com/vaadin/flow-demo/blob/e1537e280b4cd99d1f9556473a88d51be331171b/pom.xml#L171)):*
> ```XML
>             <version>1.2.17</version>
>         </dependency>
>         <dependency>
> ```

These are old WebJars, why do you need them and why do you need them here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/414)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/414)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pom.xml, line 171 at r1](https://reviewable.io:443/reviews/vaadin/flow-demo/414#-L4eVktNdgVwomTRE19b:-L4eXH-KnvXnFuE_g8_R:b-95atta) ([raw file](https://github.com/vaadin/flow-demo/blob/e1537e280b4cd99d1f9556473a88d51be331171b/pom.xml#L171)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

These are old WebJars, why do you need them and why do you need them here?
</blockquote></details>

it is needed for the `paper` Elements.. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/414)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 12 of 13 files at r2.
Review status: 14 of 15 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[demo-static-menu-router/src/main/java/com/vaadin/flow/demo/staticmenu/community/blog/BlogPost.java, line 71 at r2](https://reviewable.io:443/reviews/vaadin/flow-demo/414#-L4jGK5DbQvWOZpC3FqJ:-L4jGK5DbQvWOZpC3FqK:b5q5360) ([raw file](https://github.com/vaadin/flow-demo/blob/ee900b71f6a6d10ffd59255102e0d7a19f5a5c84/demo-static-menu-router/src/main/java/com/vaadin/flow/demo/staticmenu/community/blog/BlogPost.java#L71)):*
> ```Java
>     }
> 
>    // @Override
> ```

What's the point to leave it commented?
Either remove it or uncomment it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/414)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 13 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/414)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/414)*

**Comment by SomeoneToIgnore** [comment]
`TextFieldIT` failure might be related to `setValueChangeMode` changes.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/414#-:-L4jbHYoiwCwbEPUMG1D:bmk16ce)*

**Comment by ZheSun88** [comment]
This `TextField` is not related with `vaadin-text-field-flow` check here -> https://github.com/vaadin/flow-demo/blob/master/demo-textfield-component/src/main/java/com/vaadin/flow/demo/textfieldcomponent/TextField.java

it is a self-made component which contains an input field and a label. i am not really sure the idea to have it here. Can i remove it?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/414#-:-L4jnO5CR0NEirT8K-f-:be678f8)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/414)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 3 of 3 files at r5, 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[demo-jquery-table/src/test/java/com/vaadin/flow/demo/page/ReportsOverviewIT.java, line 97 at r6](https://reviewable.io:443/reviews/vaadin/flow-demo/414#-L4lk5Tx_fnKcwsrw9a0:-L4lk5TyOOfhXqikts7_:b-dkpi2m) ([raw file](https://github.com/vaadin/flow-demo/blob/b9152c504841c26a2aac27f16359d2927e4ca4fa/demo-jquery-table/src/test/java/com/vaadin/flow/demo/page/ReportsOverviewIT.java#L97)):*
> ```Java
>         // sort the first list and compare it with the list sorted by jquery
>         Collections.sort(idsBeforeJQuerySort);
>         System.out.println(idsBeforeJQuerySort);
> ```

This is definitely not needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/414)*

**Comment by ZheSun88** [comment]
Review status: 19 of 20 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo-jquery-table/src/test/java/com/vaadin/flow/demo/page/ReportsOverviewIT.java, line 97 at r6](https://beta.reviewable.io/reviews/vaadin/flow-demo/414#-L4lk5Tx_fnKcwsrw9a0:-L4lkcJK1ReMKGft6XwX:b8t7wx1) ([raw file](https://github.com/vaadin/flow-demo/blob/b9152c504841c26a2aac27f16359d2927e4ca4fa/demo-jquery-table/src/test/java/com/vaadin/flow/demo/page/ReportsOverviewIT.java#L97)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

This is definitely not needed.
</blockquote></details>

oh my ... sorry for that..

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-demo/414)*

**Comment by ZheSun88** [comment]
this header issue comes back again....

---

Review status: 19 of 20 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-demo/414#-:-L4lnaOB5BpEVVJu6vrj:btek6hh)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 1 files at r7, 2 of 2 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/flow-demo/414)*

**Pull request merged**
