### PR TITLE
Added view to create a new blog entry.

### PR DESCRIPTION
**Pull request by caalador**
New blog entry shows the functioning of postpone
when there are changes in the fields and user tries
to navigate away.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/flow-demo/376)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[demo-static-menu-router/src/main/java/com/vaadin/flow/demo/staticmenu/community/blog/ConfirmationDialog.java, line 100 at r1](https://reviewable.io:443/reviews/vaadin/flow-demo/376#-KwiQss4SAofsYtLMi9C:-KwiQss4SAofsYtLMi9D:b-d0wxhj) ([raw file](https://github.com/vaadin/flow-demo/blob/b2e7ed227d34f5436bfd9eb54ec168b681e3a070/demo-static-menu-router/src/main/java/com/vaadin/flow/demo/staticmenu/community/blog/ConfirmationDialog.java#L100)):*
> ```Java
>         getElement().removeFromParent();
>     }
> }
> ```

new line

---

*[demo-static-menu-router/src/main/java/com/vaadin/flow/demo/staticmenu/community/blog/backend/BlogsService.java, line 58 at r1](https://reviewable.io:443/reviews/vaadin/flow-demo/376#-KwiSIAQbzPYBOO5odu0:-KwiSIAQbzPYBOO5odu1:bfaqt94) ([raw file](https://github.com/vaadin/flow-demo/blob/b2e7ed227d34f5436bfd9eb54ec168b681e3a070/demo-static-menu-router/src/main/java/com/vaadin/flow/demo/staticmenu/community/blog/backend/BlogsService.java#L58)):*
> record.setDate(LocalDateTime.now());

One more aspect of synchronization: data should be thread safe as well.
API-opened setter makes it possible to modify data without synchronization. Which makes it's not thread-safe.

I would recommend to set Date in the CTOR.
All fields in record should be effectively final.
So they either should be really `final` or they should not be modified after they has been set.
Otherwise they also requires synchronization.

---

*[demo-static-menu-router/src/main/java/com/vaadin/flow/demo/staticmenu/community/blog/backend/BlogsService.java, line 62 at r1](https://reviewable.io:443/reviews/vaadin/flow-demo/376#-KwiROIvoiQSnXZgo-FN:-KwiROIvoiQSnXZgo-FO:b-dozzvv) ([raw file](https://github.com/vaadin/flow-demo/blob/b2e7ed227d34f5436bfd9eb54ec168b681e3a070/demo-static-menu-router/src/main/java/com/vaadin/flow/demo/staticmenu/community/blog/backend/BlogsService.java#L62)):*
> synchronized (records) {
>             record.setId(records.size() + 1);
>             records.add(record);
>         }

Several things here:
- technically it's correct but the class is not thread safe in its other parts. So either it should be made thread safe or it doesn't make sense to synchronize
- in case it should be thread safe there is no need to synchronize of `records` . `records` is 1:1 with the class instance . So it's technically the same as synchronized `saveItem` method.
- `getRecord` has to be synchronized as well ( either in the same way as here or just synchronized as I suggested).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/376)*

**Comment by caalador** [comment]
Review status: 11 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[demo-static-menu-router/src/main/java/com/vaadin/flow/demo/staticmenu/community/blog/ConfirmationDialog.java, line 100 at r1](https://reviewable.io:443/reviews/vaadin/flow-demo/376#-KwiQss4SAofsYtLMi9C:-KwiVnc7Og3frh_RdlsJ:b-896fix) ([raw file](https://github.com/vaadin/flow-demo/blob/b2e7ed227d34f5436bfd9eb54ec168b681e3a070/demo-static-menu-router/src/main/java/com/vaadin/flow/demo/staticmenu/community/blog/ConfirmationDialog.java#L100)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

new line
</blockquote></details>

Done.

---

*[demo-static-menu-router/src/main/java/com/vaadin/flow/demo/staticmenu/community/blog/backend/BlogsService.java, line 58 at r1](https://reviewable.io:443/reviews/vaadin/flow-demo/376#-KwiSIAQbzPYBOO5odu0:-KwiWLhCWVW8NiwlKlvv:by1wt8c) ([raw file](https://github.com/vaadin/flow-demo/blob/b2e7ed227d34f5436bfd9eb54ec168b681e3a070/demo-static-menu-router/src/main/java/com/vaadin/flow/demo/staticmenu/community/blog/backend/BlogsService.java#L58)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> record.setDate(LocalDateTime.now());

One more aspect of synchronization: data should be thread safe as well.
API-opened setter makes it possible to modify data without synchronization. Which makes it's not thread-safe.

I would recommend to set Date in the CTOR.
All fields in record should be effectively final.
So they either should be really `final` or they should not be modified after they has been set.
Otherwise they also requires synchronization.
</blockquote></details>

In this instance it's not the creation of the record that should be marked, but at save time eg. database should handle it.

---

*[demo-static-menu-router/src/main/java/com/vaadin/flow/demo/staticmenu/community/blog/backend/BlogsService.java, line 62 at r1](https://reviewable.io:443/reviews/vaadin/flow-demo/376#-KwiROIvoiQSnXZgo-FN:-KwiWLKnPRsgcYYqJBal:b-896fix) ([raw file](https://github.com/vaadin/flow-demo/blob/b2e7ed227d34f5436bfd9eb54ec168b681e3a070/demo-static-menu-router/src/main/java/com/vaadin/flow/demo/staticmenu/community/blog/backend/BlogsService.java#L62)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> synchronized (records) {
>             record.setId(records.size() + 1);
>             records.add(record);
>         }

Several things here:
- technically it's correct but the class is not thread safe in its other parts. So either it should be made thread safe or it doesn't make sense to synchronize
- in case it should be thread safe there is no need to synchronize of `records` . `records` is 1:1 with the class instance . So it's technically the same as synchronized `saveItem` method.
- `getRecord` has to be synchronized as well ( either in the same way as here or just synchronized as I suggested).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/376)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/376)*

**Comment by denis-anisimov** [comment]
Reviewed 3 of 3 files at r4, 3 of 4 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/flow-demo/376)*

**Pull request merged**
